export type HelpText = { title: string; what: string; why: string };
export const help: Record<string, HelpText> = {
  Overview: {
    title: "Your review at a glance",
    what: "Start here to see the evidence, possible conflicts and review progress.",
    why: "Add what your application uses, then analyze sources to connect documented changes to your work.",
  },
  Evidence: {
    title: "Evidence cards",
    what: "Each card is an exact passage from a saved source, with a suggested category and related identifiers.",
    why: "Open a card to check its context, compare conflicting guidance and record a human decision.",
  },
  Sources: {
    title: "Original documents",
    what: "Keep versioned release notes and reference text together. Paste text or import public GitHub release notes. PDF, Word and source-folder uploads are not supported.",
    why: "Every finding and citation points back here. Adding a source requires fresh analysis.",
  },
  Graph: {
    title: "Connections in the evidence",
    what: "Explore links between sources, findings, technical identifiers and application components.",
    why: "Graph relationships help you trace why a change might matter and retrieve evidence beyond matching words.",
  },
  Questions: {
    title: "Questions saved with your review",
    what: "Search analyzed evidence and optionally generate a cited answer with the configured model.",
    why: "These answers become part of the shared snapshot. Use Assistant for a private, temporary workflow conversation.",
  },
  Activity: {
    title: "Team review history",
    what: "See the latest 200 saved changes, including who submitted them and when.",
    why: "This makes review progress traceable. Display names are session labels, not verified identities.",
  },
  analysis: {
    title: "Analyze sources",
    what: "Creates evidence cards, suggested categories, topics, entity links and possible conflicts from your saved text.",
    why: "Run again after changing sources or application usage. Suggestions support review; they do not prove upgrade safety.",
  },
  usage: {
    title: "What your application uses",
    what: "Declare a component and the exact setting or API it depends on, such as Checkout service and retry_limit.",
    why: "These links help mark relevant findings and connect your application to graph retrieval. No source code is scanned.",
  },
  topics: {
    title: "Topics in this review",
    what: "NMF topic modeling groups similar passages and displays representative words.",
    why: "Use a topic as a starting point for exploration. It is a text pattern, not a risk or priority score.",
  },
  conflicts: {
    title: "Possible conflicting guidance",
    what: "Rules flag opposite removal/support statements about the same identifier and version.",
    why: "Read both original passages and investigate. No conflict found does not mean the upgrade is safe.",
  },
  reviewed: {
    title: "Review progress",
    what: "Counts findings with a saved human decision and optional review note.",
    why: "A recorded decision is progress, not automatic approval. Reassess it when sources or usage change.",
  },
  theme: {
    title: "Appearance",
    what: "Choose Light, Dark, or System to follow your device's appearance.",
    why: "Your choice is remembered in this browser and does not change anyone else's workspace.",
  },
  workspaces: {
    title: "Saved workspaces",
    what: "Create a fresh review or reopen another saved review, including leaving the example.",
    why: "Saved work is preserved. Switching changes the active review for everyone connected; unsaved inputs close.",
  },
  tutorial: {
    title: "Beginner tutorial",
    what: "Walk through a prepared example with Next, Back and replayable demonstrations.",
    why: "Learn the goal and workflow without changing your real review or calling the model.",
  },
  export: {
    title: "Export snapshot",
    what: "Download this review as JSON with sources, findings, answers and review notes.",
    why: "Open it later or share it for review. It includes document text and reviewer names, so check it before sharing.",
  },
  import: {
    title: "Import a saved review",
    what: "Open a validated Release Atlas JSON snapshot, not a PDF, Word file or source folder.",
    why: "When signed in, the import creates a separate workspace. In a saved-file view it replaces the current view.",
  },
  sourceTitle: {
    title: "Source title",
    what: "Give the document a recognizable title, such as Harbor 2.0 release notes.",
    why: "This title appears beside findings and citations so reviewers can trace the evidence.",
  },
  version: {
    title: "Document version",
    what: "Record the release version the document describes.",
    why: "Older documentation does not prove current behavior. Conflict checks compare matching version labels.",
  },
  url: {
    title: "Source reference link",
    what: "An optional link to the original publication for a reviewer to open.",
    why: "This is a reference only. Paste the document into Source text; the URL does not fetch its content.",
  },
  rights: {
    title: "Permission to use the text",
    what: "Record the document's license or your permission to use and share it.",
    why: "Source text travels with exports. Only add material you are allowed to use in this workspace.",
  },
  sourceText: {
    title: "Documentation text",
    what: "Paste release notes or reference text, with one passage per line and exact identifier spellings.",
    why: "Analysis quotes this text directly. Keep the version and wording intact so reviewers can verify every finding.",
  },
  saveSource: {
    title: "Save this source",
    what: "Stores the versioned text and a content fingerprint in the shared workspace.",
    why: "Saving invalidates earlier analysis. Analyze again to incorporate the new source into findings and answers.",
  },
  feed: {
    title: "Public GitHub release feed",
    what: "Fetch up to three release-note entries from an owner/repository pair.",
    why: "This imports documentation snapshots, not repository source code. Each entry retains its version and origin.",
  },
  search: {
    title: "Search the evidence",
    what: "Filter cards by words or identifiers in their quoted text.",
    why: "This only changes the visible list. It does not modify sources, findings or saved reviews.",
  },
  category: {
    title: "Suggested change category",
    what: "A statistical classifier labels passages as breaking, deprecation, security, feature, fix or other.",
    why: "Use it to narrow the list, then read the passage. Categories and scores are not verified risk judgments.",
  },
  scope: {
    title: "Focus your review",
    what: "Show all findings, usage matches, conflict candidates or findings without a saved review.",
    why: "These filters organize attention without discarding evidence or changing team decisions.",
  },
  decision: {
    title: "Your review decision",
    what: "Choose whether the finding applies to your usage or still needs investigation.",
    why: "The decision becomes shared review evidence when you save it. Explain your reasoning in the note.",
  },
  note: {
    title: "Review note",
    what: "Describe what you checked, what you concluded, and any remaining follow-up.",
    why: "The note gives teammates context beyond a status label and is included in snapshots.",
  },
  saveReview: {
    title: "Save review",
    what: "Records your decision, note and display name for this evidence card.",
    why: "Other sessions receive the update. Stale drafts are blocked so a colleague's newer work is not overwritten.",
  },
  currentReview: {
    title: "Load the current review",
    what: "Replace this draft with the latest saved decision and note.",
    why: "Use this after a teammate changes the workspace. Copy any unsaved text you want to keep first.",
  },
  sourcePosition: {
    title: "Exact quote location",
    what: "Character positions identify the passage inside the saved source text.",
    why: "They let the app verify quotation integrity on import. Integrity does not prove the source itself is correct.",
  },
  fingerprint: {
    title: "Content fingerprint",
    what: "A SHA-256 hash identifies the saved document text.",
    why: "It helps detect changed text during import and keep citations consistent. It is not a trust rating.",
  },
  retrieval: {
    title: "How evidence is found",
    what: "Lexical uses word overlap. Vector uses statistical text similarity. Graph adds paths through entities and application components.",
    why: "Compare methods to understand why a passage was retrieved. A high score is not proof of relevance or truth.",
  },
  generation: {
    title: "Generate a cited answer",
    what: "Send the question and retrieved passages to the server's configured language model.",
    why: "The app validates citation IDs, but you still need to check whether each quote supports the answer.",
  },
  ask: {
    title: "Ask the evidence",
    what: "Retrieve supporting passages, optionally generate an answer, and save it with the shared review.",
    why: "Analysis must be current. The answer and its citations are included in exports for later checking.",
  },
  citation: {
    title: "Follow a citation",
    what: "Open the evidence card supporting this answer.",
    why: "Read its original quote and version before trusting the summary, especially when sources disagree.",
  },
  graphNode: {
    title: "Explore a graph connection",
    what: "Select a node to inspect its type and neighboring relationships.",
    why: "Connections explain how your application's usage reaches the documented findings.",
  },
  signin: {
    title: "Join the shared review",
    what: "Use a display name and the workspace access code to collaborate.",
    why: "This enables saved edits, analysis and model chat. The code is shared access, not an individual account password.",
  },
  signout: {
    title: "End this session",
    what: "Sign out of the live workspace in this browser.",
    why: "Saved team work remains available. Unsaved inputs and your temporary assistant conversation are not shared records.",
  },
  assistant: {
    title: "Ask Atlas",
    what: "Get explanations, workflow guidance, or answers about the page and selected evidence.",
    why: "The chat follows your workspace but does not change it. Conversation stays in this open view and is not exported.",
  },
  assistantMode: {
    title: "Choose how Atlas helps",
    what: "Model chat can answer open-ended questions using the configured language model and relevant workspace context. App guide uses built-in help.",
    why: "App guide works without a model. Neither mode changes your review or saves shared decisions.",
  },
  chatPrompt: {
    title: "Start a conversation",
    what: "Send this suggested question using the selected assistant mode.",
    why: "The reply uses your current page and workspace. You can follow up in your own words.",
  },
  chatMessage: {
    title: "Message Atlas",
    what: "Ask about a control, a workflow, a selected finding, or a general concept. Enter sends; Shift+Enter adds a new line.",
    why: "Model chat sends bounded conversation history and relevant workspace text to the configured provider. Check evidence before relying on an answer.",
  },
  clearChat: {
    title: "Clear this conversation",
    what: "Remove the messages in this browser's current assistant view.",
    why: "This does not delete sources, reviews or answers saved in Questions. Refreshing or switching workspaces also clears chat.",
  },
  stopChat: {
    title: "Stop waiting for a response",
    what: "Cancel this browser's pending answer and keep your draft.",
    why: "No review is changed. The provider may finish its current request before another model request can start.",
  },
  closeChat: {
    title: "Close the assistant",
    what: "Hide this panel and return to your review. Reopen Ask Atlas to continue the conversation.",
    why: "Messages stay while you navigate pages in this workspace. They are not saved in exported reviews.",
  },
  close: {
    title: "Close this panel",
    what: "Return to the review without submitting a change.",
    why: "Save any form changes first if you want to keep them.",
  },
};
export const helpLabels: Record<string, string> = {
  Overview: "Overview",
  Evidence: "Evidence",
  Sources: "Sources",
  Graph: "Graph",
  Questions: "Questions",
  Activity: "Activity",
  Appearance: "theme",
  "Snapshot fingerprint": "fingerprint",
  "How this was produced": "category",
  "Open original source": "url",
  "Fetch release snapshots": "feed",
  "Your question": "ask",
  "Focus on an entity or component": "graphNode",
  "Go to Sources": "Sources",
  "Assistant mode": "assistantMode",
  "Message Atlas": "chatMessage",
  "Send message": "chatMessage",
  "Stop response": "stopChat",
  "Close assistant": "closeChat",
  "Use App guide": "assistantMode",
  "Analyze sources": "analysis",
  "Analyzing…": "analysis",
  Workspaces: "workspaces",
  "Leave example / switch workspace": "workspaces",
  "New empty workspace": "workspaces",
  "New workspace name": "workspaces",
  "Beginner tutorial": "tutorial",
  "Start beginner tutorial": "tutorial",
  "Try the beginner tutorial": "tutorial",
  "Export snapshot": "export",
  Import: "import",
  "Import saved analysis": "import",
  "Edit usage profile": "usage",
  "Save profile": "usage",
  "One component | identifier per line": "usage",
  "Source title": "sourceTitle",
  Version: "version",
  "Source URL (optional)": "url",
  "License / permission": "rights",
  "License or permission for the release text": "rights",
  "Source text": "sourceText",
  "Save source": "saveSource",
  Repository: "feed",
  "Import releases": "feed",
  "Import a public GitHub release feed": "feed",
  "Search evidence": "search",
  Category: "category",
  "Evidence scope": "scope",
  Decision: "decision",
  "Review note": "note",
  "Save review": "saveReview",
  "Load current review": "currentReview",
  "Read the other claim": "conflicts",
  "Review all open evidence": "Evidence",
  "Add your first source": "Sources",
  "Retrieval method": "retrieval",
  "Use language model": "generation",
  "Ask the evidence": "ask",
  Question: "ask",
  "Sign out": "signout",
  "Display name": "signin",
  "Workspace access code": "signin",
  "Enter workspace": "signin",
  "Sign in to collaborate": "signin",
  Close: "close",
  "Close sign in": "close",
  "Close workspaces": "close",
  "Evidence cards": "Evidence",
  "Match your usage": "usage",
  "Conflicting claims": "conflicts",
  Reviewed: "reviewed",
};
